### ISSUE TITLE
myUserDetailsService 加载不到

### ISSUE THREAD

**Issue by zhongqishang** [spring-security/spring-security-mybatis-login-remember-me#1]
我参考这个项目的做法，自己做了一个，可是我的myUserDetailsService是加载不上去的，不知道为什么，能帮我看一下吗、
https://github.com/gladoffice/office

**Comment by pengfeinie** [comment]
请参考我的这篇博客：http://blog.csdn.net/pfnie/article/details/56301830

**Comment by zhongqishang** [comment]
。
